# **Lesson 1.Numpy 기초_예제**
데이터 분석 초급 과정 2 (Python) > Module1. 데이터 분석을 위한 Python 라이브러리

## **(1) 환경준비**

### **1) 라이브러리 불러오기**
- Numpy 배열을 사용하려면 우선 **Numpy** 라이브러리를 불러와야 합니다.
- Numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [ ]:
import numpy as np
import pandas as pd

### **2) 데이터 로딩**

* 매장이 있는 각 지역별 데이터

|	변수명	|	설명	|	구분	|
|----|----|----|
|	Sales 	|	 각 지역 판매량(단위 : 1000개)	|	Target	|
|	CompPrice 	|	지역별 경쟁사 판매가격(달러)	|	feature	|
|	Advertising 	|	 각 지역, 회사의 광고 예산(단위 : 1000달러)	|	feature	|
|	Population 	|	 지역 인구수(단위 : 1000명)	|	feature	|
|	Price 	|	 자사 지역별 판매가격(달러)	|	feature	|
|	ShelveLoc 	|	 진열상태	|	feature	|
|	Age 	|	 지역 인구의 평균 연령	|	feature	|
|	US 	|	 매장이 미국에 있는지 여부	|	feature	|
|	Urban 	|	 매장이 도시에 있는지 여부	|	feature	|
|	Education 	|	 평균학력수준(범주 : 10 ~ 18)	|	feature	|

In [ ]:
path = 'carseat.csv'  # 제공된 데이터 로딩
carseat = pd.read_csv(path)

----

## **(2) Topic 1. Numpy 소개**

### **1) 분석 가능한 데이터 구조**

* 2차원 형태의 데이터 구조 살펴보기

In [ ]:
carseat.head()

### **2) Numpy로 구조 살펴보기**

In [ ]:
print(np.array(carseat))

----

## **(3) Topic 2. 배열 생성하고 다루기**


### 1) 배열 생성하기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합시다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array
- shape는 (3, 4)

In [ ]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

In [ ]:
# 2차원 리스트
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2],
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

In [ ]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)

### **2) 배열 속성 확인하기**

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

<img src='https://github.com/DA4BAM/image/blob/main/1,2,3%20%EC%B0%A8%EC%9B%90.png?raw=true' width=800 align="left"/>

* **차원 확인**
    - ndim 속성으로 배열 차원을 확인합니다.

In [ ]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

* **형태(크기) 확인**
    - shape 속성으로 배열 형태를 확인합니다.
    - 결과는 다음과 같은 형태의 튜플로 표시됩니다.
        - 1차원: (x, )
        - 2차원: (x, y)
        - 3차원: (x, y, z)
    - 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [ ]:
# 형태(크기) 확인
print(b1.shape)
print(b2.shape)
print(b3.shape)

* **요소 자료형 확인**
    - dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다.
    - 배열은 한 가지 자료형만 가질 수 있다는 특징이 있습니다.

In [ ]:
# 요소 자료형 형식 확인
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)

### **3) 배열 형태 변경하기(reshape)**

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 됩니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

* **(2, 3) → (3, 2)**

In [ ]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2) # np.array(a, (3,2))

# 확인
print(b)

* **(2, 3) → (6,)**

In [ ]:
# 1차원 배열로 Reshape
# c = a.reshape(6,)
c = a.reshape(6)

# 확인
print(c)

* **-1의 편리성**

    - **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 확인
print(a)

In [ ]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능
print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))

## **(4) Topic 3. 배열 조회하기**

### **1) 인덱스로 조회하기**

In [ ]:
# 배열 생성
a = np.array([23, 3, 16, 45, 11])
print(a)

In [ ]:
# 조회1
print(a[0], a[3])

In [ ]:
# 조회2
print(a[-1], a[-3])

In [ ]:
# 2차원 배열 만들기
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# 확인
print(b)

In [ ]:
# 첫 번째 행, 두 번째 열 요소 조회
print(b[0, 1])

In [ ]:
# 행 인덱스로 조회(열 인덱스 생략)
print(b[1])

### **2) 범위 조회(슬라이싱)**

* 1차원 배열의 범위 조회

In [ ]:
# 1차원 배열 만들기
a = np.array([23, 3, 16, 45, 11])

# 확인
print(a)

In [ ]:
# 조회1
print(a[1:4])

In [ ]:
# 조회2 : 시작인덱스 생략
print(a[:2])

In [ ]:
# 조회3 : 끝인덱스 생략
print(a[2:])

* 2차원 배열 범위 조회

In [ ]:
# 2차원 배열 만들기
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# 확인
print(b)

In [ ]:
# 행 범위 조회
print(b[1:3])

In [ ]:
# 열 인덱스로 조회
print(b[:, 1])

In [ ]:
# 열 범위 조회
print(b[:, 0:2])

In [ ]:
# 행, 열 범위 조회
print(b[1:3, 0:2])

### **3) 조건조회**

* 조건문

In [ ]:
# 1차원 배열 만들기
a = np.array([23, 3, 16, 45, 11])

# 확인
print(a)

In [ ]:
# 조건문
print(a >= 20)

* 조건조회

In [ ]:
print(a[a >= 20])

## **(5) Topic 4. 배열 연산**

### **1) 집계함수 사용하기**

* 기본 연산(사칙연산)

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.png?raw=true' width=600 align="left"/>

In [ ]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

[[1 2]

 [3 4]]

[[5 6]

 [7 8]]


In [ ]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

[[ 6  8]

 [10 12]]

[[ 6  8]

 [10 12]]


In [ ]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

[[-4 -4]

 [-4 -4]]

[[-4 -4]

 [-4 -4]]


In [ ]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

[[ 5 12]

 [21 32]]

[[ 5 12]

 [21 32]]


In [ ]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

[[0.2        0.33333333]

 [0.42857143 0.5       ]]

[[0.2        0.33333333]

 [0.42857143 0.5       ]]


* 배열 내 집계함수
    - np.sum()
        * axis = 0 : 열 기준 집계
        * axis = 1 : 행 기준 집계
        * 생략하면 : 전체 집계
    - 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [ ]:
a = np.array([[1,5,7],[2,3,8]])
print(a)

[[1 5 7]

 [2 3 8]]


In [ ]:
# 전체 집계
print(np.sum(a))

# 행 방향 집계
print(np.sum(a, axis = 0))

# 열 방향 집계
print(np.sum(a, axis = 1))

26

[ 3  8 15]

[13 13]


### **2) 유용한 함수들**

* **가장 큰(작은) 값의 인덱스**

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4_argmin.png?raw=true' width=800 align="left"/>

In [ ]:
print(a)
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최댓값의 인덱스
print(np.argmax(a, axis = 0))

# 열 방향 최댓값의 인덱스
print(np.argmax(a, axis = 1))


[[1 5 7]

 [2 3 8]]

5

[1 0 1]

[2 2]


* **조건에 따라 다른 값 지정하기**

    * np.where(조건문, True일때 값, False일 때 값)

In [ ]:
# 선언
a = np.array([1,3,2,7])

# 조건
np.where(a > 2, 1, 0)

array([0, 1, 0, 1])