# **Topic 3. 배열 조회하기_실습**

## **(1) 환경준비**


### **1) 라이브러리 로딩**

In [ ]:
import numpy as np

### **2) 데이터 준비**

In [ ]:
a = np.array([[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]])

## **(2) 실습문제**
위 배열을 이용하여 실습문제를 푸시오.

### 1) 실습1 : 인덱스 조회
* 다음의 결과를 얻도록 조회하시오.
    * 16
    * [19 20 21 22]
    * [13 17 21]

In [ ]:
# 16
a[1,1]

16

In [ ]:
# [19 20 21 22]
a[2]

array([19, 20, 21, 22])

In [ ]:
# [13 17 21]
a[:,2]

array([13, 17, 21])

### 2) 실습2 : 범위조회(슬라이싱)

* 다음의 결과를 얻도록 조회하시오.
    * [[15 16 17 18]  
      [19, 20, 21, 22]]
    * [[16 17]  
      [20 21]]

In [ ]:
# [[15 16 17 18]
# [19, 20, 21, 22]]
print(a[1:])

[[15 16 17 18]
 [19 20 21 22]]


In [ ]:
# [[16 17]
# [20 21]]
print(a[1:, 1:3])

[[16 17]
 [20 21]]


### 3) 실습3 : 조건조회

* 17보다 큰 값을 조회하시오.
    * 조건문의 결과 출력
    * 조건문에 해당되는 값 조회

In [ ]:
# 조건문
print(a > 17)

[[False False False False]
 [False False False  True]
 [ True  True  True  True]]


In [ ]:
# 조건조회
print(a[a > 17])

[18 19 20 21 22]
